"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
exports.__esModule = true;
var data_source_js_1 = require("../data-source.js");
var Show_js_1 = require("../entities/Show.js");
var Person_js_1 = require("../entities/Person.js");
data_source_js_1["default"].initialize();
var sync = function () { return __awaiter(void 0, void 0, void 0, function () { return __generator(this, function (_a) {
    switch (_a.label) {
        case 0: return [4 /*yield*/, data_source_js_1["default"].synchronize()];
        case 1: return [2 /*return*/, _a.sent()];
    }
}); }); };
sync();
var personRepo = data_source_js_1["default"].getRepository(Person_js_1.Person);
var showRepo = data_source_js_1["default"].getRepository(Show_js_1.Show);
var person1 = new Person_js_1.Person();
person1.id = "1a";
person1.username = "test";
person1.password = "asf;lkwje";
var show1 = new Show_js_1.Show();
show1.id = 'asdwef;lk';
show1.title = 'Stranger Things';
show1.streamingApp = 'Hulu';
show1.rating = 4.5;
show1.review = 'excellent movie';
show1.person = person1;
showRepo.save(show1);
var person2 = new Person_js_1.Person();
person2.id = "1c";
person2.username = "test2";
person2.password = "sdf;lkwe";
personRepo.save(person2);
var show2 = new Show_js_1.Show();
show2.id = 'asdfwe;lk';
show2.title = 'The Crown';
show2.streamingApp = 'Amazon';
show2.rating = 4.0;
show2.review = 'great movie';
show2.person = person2;
showRepo.save(show2);
//
var show3 = new Show_js_1.Show();
show3.id = 'asdfl;kwe';
show3.title = 'Westworld';
show3.streamingApp = 'HBO';
show3.rating = 4.2;
show3.review = 'interesting movie';
show3.person = person1;
showRepo.save(show3);
var show4 = new Show_js_1.Show();
show4.id = 'asdfl;kae';
show4.title = 'The Mandalorian';
show4.streamingApp = 'Disney+';
show4.rating = 4.7;
show4.review = 'amazing movie';
show4.person = person2;
showRepo.save(show4);
var show5 = new Show_js_1.Show();
show5.id = 'asdfl;kfe';
show5.title = 'Vikings';
show5.streamingApp = 'Amazon';
show5.rating = 3.9;
show5.review = 'good movie';
show5.person = person2;
showRepo.save(show5);
var show6 = new Show_js_1.Show();
show6.id = 'asdfl;kge';
show6.title = 'The Boys';
show6.streamingApp = 'Amazon';
show6.rating = 4.3;
show6.review = 'awesome movie';
show6.person = person1;
showRepo.save(show6);
var show7 = new Show_js_1.Show();
show7.id = 'asdfl;khe';
show7.title = 'Dark';
show7.streamingApp = 'Netflix';
show7.rating = 4.1;
show7.review = 'great movie';
show7.person = person2;
showRepo.save(show7);
var show8 = new Show_js_1.Show();
show8.id = 'asdfl;kie';
show8.title = 'The Witcher';
show8.streamingApp = 'Netflix';
show8.rating = 4.2;
show8.review = 'fantastic movie';
show8.person = person1;
showRepo.save(show8);
var show9 = new Show_js_1.Show();
show9.id = 'asdfl;kje';
show9.title = 'House of Cards';
show9.streamingApp = 'Netflix';
show9.rating = 3.8;
show9.review = 'good movie';
show9.person = person2;
showRepo.save(show9);
var show10 = new Show_js_1.Show();
show10.id = 'asdfl;kke';
show10.title = 'Breaking Bad';
show10.streamingApp = 'Netflix';
show10.rating = 4.8;
show10.review = 'brilliant movie';
show10.person = person1;
showRepo.save(show10);
var show11 = new Show_js_1.Show();
show11.id = 'asdfl;kle';
show11.title = 'Mindhunter';
show11.streamingApp = 'Netflix';
show11.rating = 4.4;
show11.review = 'amazing movie';
show11.person = person2;
showRepo.save(show11);
var show12 = new Show_js_1.Show();
show12.id = 'asdfl;kme';
show12.title = 'Peaky Blinders';
show12.streamingApp = 'Netflix';
show12.rating = 4.6;
show12.review = 'great movie';
show12.person = person1;
showRepo.save(show12);
var show13 = new Show_js_1.Show();
show13.id = 'asdfl;kne';
show13.title = 'Narcos';
show13.streamingApp = 'Netflix';
show13.rating = 4.1;
show13.review = 'excellent movie';
show13.person = person2;
showRepo.save(show13);
var show14 = new Show_js_1.Show();
show14.id = 'asdfl;koe';
show14.title = 'Sherlock';
show14.streamingApp = 'Netflix';
show14.rating = 4.5;
show14.review = 'great movie';
show14.person = person1;
showRepo.save(show14);
var show15 = new Show_js_1.Show();
show15.id = 'jlkjgfwe';
show15.title = 'FRIENDS';
show15.streamingApp = 'Hulu';
show15.rating = 4.7;
show15.review = 'awesome show';
show15.person = person2;
showRepo.save(show15);
var show16 = new Show_js_1.Show();
show16.id = 'qwertyasdf';
show16.title = 'Game of Thrones';
show16.streamingApp = 'HBO';
show16.rating = 4.9;
show16.review = 'fantastic series';
show16.person = person1;
showRepo.save(show16);
var show17 = new Show_js_1.Show();
show17.id = 'poiuytrewq';
show17.title = 'Breaking Bad';
show17.streamingApp = 'Netflix';
show17.rating = 4.8;
show17.review = 'mind-blowing show';
show17.person = person2;
showRepo.save(show17);
var show18 = new Show_js_1.Show();
show18.id = 'lkjhgfdsa';
show18.title = 'Friends';
show18.streamingApp = 'Netflix';
show18.rating = 4.3;
show18.review = 'funny sitcom';
show18.person = person1;
showRepo.save(show18);
var show19 = new Show_js_1.Show();
show19.id = 'mnbvcxzas';
show19.title = 'Stranger Things';
show19.streamingApp = 'Netflix';
show19.rating = 4.7;
show19.review = 'scary and thrilling';
show19.person = person2;
showRepo.save(show19);
var show20 = new Show_js_1.Show();
show20.id = 'zxcvbnmlk';
show20.title = 'The Crown';
show20.streamingApp = 'Netflix';
show20.rating = 4.2;
show20.review = 'engaging drama';
show20.person = person1;
showRepo.save(show20);
var show21 = new Show_js_1.Show();
show21.id = 'poiuytrew';
show21.title = 'Westworld';
show21.streamingApp = 'HBO';
show21.rating = 4.4;
show21.review = 'thought-provoking show';
show21.person = person2;
showRepo.save(show21);
var show22 = new Show_js_1.Show();
show22.id = 'lkjhgfdsq';
show22.title = 'Black Mirror';
show22.streamingApp = 'Netflix';
show22.rating = 4.5;
show22.review = 'intriguing show';
show22.person = person1;
showRepo.save(show22);
var show23 = new Show_js_1.Show();
show23.id = 'mnbvcxzpo';
show23.title = 'The Twilight Zone';
show23.streamingApp = 'CBS All Access';
show23.rating = 4.0;
show23.review = 'mysterious and suspenseful';
show23.person = person2;
showRepo.save(show23);
var show24 = new Show_js_1.Show();
show24.id = 'zxcvbnmli';
show24.title = 'The Office';
show24.streamingApp = 'Netflix';
show24.rating = 4.7;
show24.review = 'hilarious comedy';
show24.person = person1;
showRepo.save(show24);
var show25 = new Show_js_1.Show();
show25.id = 'qwertyuiop';
show25.title = 'The Handmaid\'s Tale';
show25.streamingApp = 'Hulu';
show25.rating = 4.1;
show25.review = 'powerful and disturbing';
show25.person = person2;
showRepo.save(show25);
var show26 = new Show_js_1.Show();
show26.id = 'asdfghjkl;';
show26.title = 'The Walking Dead';
show26.streamingApp = 'AMC';
show26.rating = 4.0;
show26.review = 'brutal and shocking';
show26.person = person1;
showRepo.save(show26);
var show27 = new Show_js_1.Show();
show27.id = 'zxcvbnm,.';
show27.title = 'True Detective';
show27.streamingApp = 'HBO';
show27.rating = 4.3;
show27.review = 'intense and mysterious';
show27.person = person2;
showRepo.save(show27);
var show28 = new Show_js_1.Show();
show28.id = 'qwertyuiop';
show28.title = 'The West Wing';
show28.streamingApp = 'Netflix';
show28.rating = 4.6;
show28.review = 'inspiring political drama';
show28.person = person1;
showRepo.save(show28);
var show29 = new Show_js_1.Show();
show29.id = 'lkjhgfdsa';
show29.title = 'Fringe';
show29.streamingApp = 'Hulu';
show29.rating = 4.2;
show29.review = 'weird and mysterious';
show29.person = person2;
showRepo.save(show29);
var show30 = new Show_js_1.Show();
show30.id = 'mnbvcxzas';
show30.title = 'The X-Files';
show30.streamingApp = 'Hulu';
show30.rating = 4.5;
show30.review = 'supernatural drama';
show30.person = person1;
showRepo.save(show30);
