export const SHOW_LIST_REQUEST = "SHOW_LIST_REQUEST";
export const SHOW_LIST_SUCCESS = "SHOW_LIST_SUCCESS";
export const SHOW_LIST_FAIL = "SHOW_LIST_FAIL";

export const SHOW_DETAILS_REQUEST = "SHOW_DETAILS_REQUEST";
export const SHOW_DETAILS_SUCCESS = "SHOW_DETAILS_SUCCESS";
export const SHOW_DETAILS_FAIL = "SHOW_DETAILS_FAIL";

export const SHOW_DELETE_REQUEST = "SHOW_DELETE_REQUEST";
export const SHOW_DELETE_SUCCESS = "SHOW_DELETE_SUCCESS";
export const SHOW_DELETE_FAIL = "SHOW_DELETE_FAIL";

export const SHOW_CREATE_REQUEST = "SHOW_CREATE_REQUEST";
export const SHOW_CREATE_SUCCESS = "SHOW_CREATE_SUCCESS";
export const SHOW_CREATE_FAIL = "SHOW_CREATE_FAIL";
export const SHOW_CREATE_RESET = "SHOW_CREATE_RESET";

export const SHOW_UPDATE_REQUEST = "SHOW_UPDATE_REQUEST";
export const SHOW_UPDATE_SUCCESS = "SHOW_UPDATE_SUCCESS";
export const SHOW_UPDATE_FAIL = "SHOW_UPDATE_FAIL";
export const SHOW_UPDATE_RESET = "SHOW_UPDATE_RESET";

export const SHOW_CREATE_REVIEW_REQUEST = "SHOW_CREATE_REVIEW_REQUEST";
export const SHOW_CREATE_REVIEW_SUCCESS = "SHOW_CREATE_REVIEW_SUCCESS";
export const SHOW_CREATE_REVIEW_FAIL = "SHOW_CREATE_REVIEW_FAIL";
export const SHOW_CREATE_REVIEW_RESET = "SHOW_CREATE_REVIEW_RESET";

export const SHOW_TOP_REQUEST = "SHOW_TOP_REQUEST";
export const SHOW_TOP_SUCCESS = "SHOW_TOP_SUCCESS";
export const SHOW_TOP_FAIL = "SHOW_TOP_FAIL";
